#!/bin/sh

shout() { echo "$0: $*" >&2; }  # Just echo an error and the program name
barf() { shout "$*"; exit 111; }
safe() { "$@" || barf "cannot $*"; }

# =============================================================================
# Post-install hook file for configuring dotcloud server

dotcloud_get_env() {
    sed -n "/$1/ s/.*: \"\(.*\)\".*/\1/p" < "/home/dotcloud/environment.json"
}

echo "Writing the local settings file..."
cat > src/visionlouisville/local_settings.py <<EOF

import json
with open('/home/dotcloud/environment.json') as f:
    env = json.load(f)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'visionlouisville',
        'USER': env['DOTCLOUD_DB_SQL_LOGIN'],
        'PASSWORD': env['DOTCLOUD_DB_SQL_PASSWORD'],
        'HOST': env['DOTCLOUD_DB_SQL_HOST'],
        'PORT': int(env['DOTCLOUD_DB_SQL_PORT']),
    }
}

STATIC_ROOT = '/home/dotcloud/current/static/'

# Debug is False by default, true if set in the environment.
DEBUG = (env.get('DEBUG', 'False') in ['true', 'True'])
TEMPLATE_DEBUG = DEBUG

# Set these explicitly here to override whatever may have come from settings
STATIC_URL = '/static/'

# For authenticating users with Twitter
TWITTER_CONSUMER_KEY = env['TWITTER_CONSUMER_KEY']
TWITTER_CONSUMER_SECRET = env['TWITTER_CONSUMER_SECRET']

# For accessing the app's Twitter account
TWITTER_USERNAME = env['TWITTER_USERNAME']
TWITTER_ACCESS_TOKEN = env['TWITTER_ACCESS_TOKEN']
TWITTER_ACCESS_SECRET = env['TWITTER_ACCESS_SECRET']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'simple': {
            'format': '%(levelname)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    }
}
EOF

# Need to be able to import settings to run the createdbs script...
echo VIRTUAL_ENV is "$VIRTUAL_ENV"
echo PYTHONPATH is "$PYTHONPATH"
export PYTHONPATH=$PYTHONPATH:$PWD/src/
export DJANGO_SETTINGS_MODULE=visionlouisville.settings
echo "Creating database if needed..."
safe python src/scripts/dotcloud_createdbs.py

echo "Syncing the database..."
safe src/manage.py syncdb --migrate --noinput

echo "Setting up static file service..."
safe src/manage.py collectstatic --noinput

echo "Configuring nginx to serve static files..."
cat >> nginx.conf <<EOF
location /static/ { root /home/dotcloud/current ; }
EOF
